apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.java.name }}
spec:
  replicas: {{ .Values.java.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.java.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.java.name }}
    spec:
      containers:
      - name: {{ .Values.java.name }}
        image: {{ .Values.java.image.repository }}:{{ .Values.java.image.tag }}
        ports:
        - containerPort: {{ .Values.java.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.java.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.java.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.java.port }}
      nodePort: {{ .Values.java.nodePort }}
