java:
  name: java-service
  replicas: 4
  port: 8080
  nodePort: 30007
  image:
    repository: shedyvince29/java-service
    tag: v1

node:
  name: node-service
  replicas: 2
  port: 3000
  nodePort: 30008
  image:
    repository: shedyvince29/node-service
    tag: v2

python:
  name: python-service
  replicas: 2
  port: 5000
  nodePort: 30009
  image:
    repository: shedyvince29/python-service
    tag: python1
